services:
  admin:
    build: .
    container_name: synergazing-admin
    restart: unless-stopped
    volumes:
      - admin-storage-prod:/var/www/html/storage/app/public
      - ./.env:/var/www/html/.env
    environment:
      - APP_ENV=production
      - APP_URL=${APP_URL}
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=synergazing-db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AUTORUN_ENABLED=true
      - AUTORUN_LARAVEL_MIGRATION=false
      - LOG_CHANNEL=stderr
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true

volumes:
  admin-storage-prod: